### ISSUE TITLE
Not an issue but..

### ISSUE THREAD

**Issue by manthrax** [technoblogy/logic-lab#1]
Wanted to share a threejs simulation of your device.. I haven't "wired up" the logic itself, but the switches and wire connections work..

![image](https://github.com/technoblogy/logic-lab/assets/350247/0c8dc31d-db09-4ebb-9f23-71850f988c64)

**Comment by technoblogy** [comment]
Cool!

**Comment by manthrax** [comment]
Check it out! : https://manthrax.github.io/logiclab/index.html

Let me know what you think! :)

**Comment by manthrax** [comment]
Here's the repo:
https://github.com/manthrax/logiclab/
Feel free to use/embed it if you want, and thanks for the making the device/inspiring me!
